development:
  BASE_URL: 'localhost'
  BASE_URL_PORT: '3000'
  SMTP_SETTING_ADDRESS: ''
  SMTP_SETTING_PORT: ''
  SMTP_SETTING_USERNAME: ''
  SMTP_SETTING_PASSWORD: ''
  MAILER_SENDER: 'lab@ciudadanointeligente.org'
  DISQUS_SHORTNAME: 'fima-fci'
  GOOGLE_MAPS_API_KEY: 'AIzaSyB0tTPnk5MGOLM0GbYgfq-6ileL9FiTTlw'
test:
  BASE_URL: ''
  SMTP_SETTING_ADDRESS: ''
  SMTP_SETTING_PORT: ''
  SMTP_SETTING_USERNAME: ''
  SMTP_SETTING_PASSWORD: ''
  MAILER_SENDER: 'test@test.com'
  DISQUS_SHORTNAME: ''
production:
  BASE_URL: ''
  SMTP_SETTING_ADDRESS: ''
  SMTP_SETTING_PORT: ''
  SMTP_SETTING_USERNAME: ''
  SMTP_SETTING_PASSWORD: ''
  MAILER_SENDER: 'test@test.com'
  DISQUS_SHORTNAME: ''
