development:
  BASE_URL: 'localhost'
  BASE_URL_PORT: '3000'
  SMTP_SETTING_ADDRESS: ''
  SMTP_SETTING_PORT: ''
  SMTP_SETTING_USERNAME: ''
  SMTP_SETTING_PASSWORD: ''
  MAILER_SENDER: 'lab@ciudadanointeligente.org'
  DISQUS_SHORTNAME: 'fima-fci'
  GOOGLE_MAPS_API_KEY: 'AIzaSyB0tTPnk5MGOLM0GbYgfq-6ileL9FiTTlw'
  SECRET_KEY_BASE: '3d94799dac8e3b16fc1d38138eab5f2a493ca910fc312ba43d9359268ae5590c5792833816a371621a34c5fce30266042f1a8d0482d7341fd024283e5a110f4c'
  FB_APP_ID: '1852784641636272'
  FB_APP_SECRET: 'd1a8492c7940a709327f47ac3e3d10c9'
  GOOGLE_APP_ID: '621017180687-mr56mknrv6hfk24s53h2fnkdbmso7ldf.apps.googleusercontent.com'
  GOOGLE_APP_SECRET: 'v_ViR_rVa_8-9kqeMOBBIt-2'
test:
  BASE_URL: ''
  SMTP_SETTING_ADDRESS: ''
  SMTP_SETTING_PORT: ''
  SMTP_SETTING_USERNAME: ''
  SMTP_SETTING_PASSWORD: ''
  MAILER_SENDER: 'test@test.com'
  DISQUS_SHORTNAME: ''
  GOOGLE_MAPS_API_KEY: 'AIzaSyB0tTPnk5MGOLM0GbYgfq-6ileL9FiTTlw'
  SECRET_KEY_BASE: '3d94799dac8e3b16fc1d38138eab5f2a493ca910fc312ba43d9359268ae5590c5792833816a371621a34c5fce30266042f1a8d0482d7341fd024283e5a110f4c'
  FB_APP_ID: ''
  FB_APP_SECRET: ''
  GOOGLE_APP_ID: ''
  GOOGLE_APP_SECRET: ''
production:
  BASE_URL: ''
  SMTP_SETTING_ADDRESS: ''
  SMTP_SETTING_PORT: ''
  SMTP_SETTING_USERNAME: ''
  SMTP_SETTING_PASSWORD: ''
  MAILER_SENDER: 'test@test.com'
  DISQUS_SHORTNAME: ''
  GOOGLE_MAPS_API_KEY: 'AIzaSyB0tTPnk5MGOLM0GbYgfq-6ileL9FiTTlw'
  SECRET_KEY_BASE: '3d94799dac8e3b16fc1d38138eab5f2a493ca910fc312ba43d9359268ae5590c5792833816a371621a34c5fce30266042f1a8d0482d7341fd024283e5a110f4c'
  FB_APP_ID: ''
  FB_APP_SECRET: ''
  GOOGLE_APP_ID: ''
  GOOGLE_APP_SECRET: ''
